sudo: required

services:
  - docker

branches:
  only:
    - master
    - branch1

install:
  - docker build -t hnakamur/centos7 .

script:
  - docker run --entrypoint /usr/bin/uname hnakamur/centos7 -a
